### ISSUE TITLE
LinkedIn - 404 error

### ISSUE THREAD

**Issue by JuanPabloDiaz** [dindustack/dindustack-portfolio#3]
Hi Chinwendu,

it seems that your [LinkedIn URL](https://www.linkedin.com/in/dindustack) is not working.

I found you on [Nerdearla](https://nerdear.la/en/speakers/chinwendu-agbaetuo/) and would like to [connect with you](https://www.linkedin.com/in/1diazdev),

**Comment by dindustack** [comment]
Hello Juan,

It's nice to connect with you. I don't have a LinkedIn profile. I deactivated it a while back

**Comment by JuanPabloDiaz** [comment]
Gotcha. What do you use to connect? I don't have Twitter. They closed my account.


BTW, I really like your site!

**Comment by dindustack** [comment]
Hello Juan,

We can connect on Telegram - dindustack. Thank you for your kind compliment on my website.
